version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    networks:
      - odoo_network

  odoo:
    image: odoo:15
    container_name: odoo
    ports:
      - "80:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge
